// app/privacy/page.tsx
import Link from "next/link";

export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-black text-white">
      <section className="mx-auto max-w-3xl px-6 py-12 md:py-16 prose prose-invert prose-a:text-orange-300">
        {/* Przyciski nawigacyjne */}
        <div className="mb-6">
          <Link
            href="/"
            className="inline-block rounded-2xl border border-white/20 px-4 py-2 text-sm font-medium text-white/90 hover:bg-white/10 transition"
          >
            ← Home
          </Link>
        </div>

        <h1>Privacy &amp; Cookies Policy</h1>
        <p><strong>Last updated:</strong> 10 Sep 2025</p>
        <p>
          <strong>Who we are:</strong> RedHoodNova, operated by a sole trader based in the UK.<br />
          <strong>Contact:</strong>{" "}
          <a href="mailto:contact@redhoodnova.com">contact@redhoodnova.com</a>
        </p>

        <h2>1) Personal data we process</h2>
        <ul>
          <li><strong>Contact enquiries</strong> – when you write to us or submit a form (name, email, message, company).</li>
          <li><strong>Operational data</strong> – server logs and security events (IP address, user-agent, timestamps).</li>
          <li><strong>Analytics (only if you consent)</strong> – page views, device info, referrers, aggregated usage.</li>
        </ul>

        <h2>2) Purposes &amp; legal bases</h2>
        <ul>
          <li><strong>Provide and secure the site</strong> – legitimate interests (Art. 6(1)(f)).</li>
          <li><strong>Respond to enquiries / proposals</strong> – performance of a contract or steps prior (Art. 6(1)(b)).</li>
          <li><strong>Email delivery</strong> – legitimate interests; we use <strong>Zoho Mail (SMTP)</strong> to send and receive emails.</li>
          <li><strong>Analytics &amp; marketing</strong> – consent (Art. 6(1)(a)). Not loaded unless you accept cookies.</li>
        </ul>

        <h2>3) Cookies we use</h2>
        <p>
          We use essential cookies that keep the site working, and—if you allow—analytics/marketing cookies.
        </p>

        <h3>A. Essential (always active)</h3>
        <ul>
          <li><strong>Purpose:</strong> security, load balancing, basic preferences.</li>
          <li><strong>Examples:</strong> session identifiers generated by our app / hosting.</li>
          <li><strong>Duration:</strong> session → up to 12 months.</li>
          <li><strong>Legal basis:</strong> legitimate interests.</li>
        </ul>

        <h3>B. Analytics (optional)</h3>
        <ul>
          <li><strong>Provider:</strong> Google Analytics 4 (Google Ireland Ltd.).</li>
          <li><strong>Data:</strong> page views, events, device/browser info; IP anonymised.</li>
          <li><strong>Cookies:</strong> <code>_ga</code> (2 years), <code>_ga_*</code> (2 years).</li>
          <li><strong>Legal basis:</strong> consent.</li>
        </ul>

        <h3>C. Marketing (optional – if enabled in the future)</h3>
        <ul>
          <li><strong>Providers:</strong> e.g. Meta Pixel, LinkedIn Insight.</li>
          <li>Not set unless you consent and we explicitly enable them.</li>
        </ul>

        <p>
          You can change your choice anytime: <strong>Footer → “Cookie settings”</strong>.
        </p>

        <h2>4) How we obtain data</h2>
        <ul>
          <li>Directly from you (forms, email, phone).</li>
          <li>Automatically from your device (logs, essential cookies).</li>
          <li>From analytics/marketing tools <em>only after consent</em>.</li>
        </ul>

        <h2>5) Data sharing &amp; processors</h2>
        <p>We use third-party service providers under data-processing agreements:</p>
        <ul>
          <li><strong>Hosting &amp; infrastructure:</strong> (e.g. Vercel).</li>
          <li><strong>Email delivery:</strong> <strong>Zoho Mail (SMTP)</strong>.</li>
          <li><strong>Analytics:</strong> Google Analytics 4 (only after consent).</li>
        </ul>
        <p>We do not sell personal data.</p>

        <h2>6) International transfers</h2>
        <p>
          Our providers may process data outside the UK/EEA. Where they do, they rely on adequacy decisions or Standard
          Contractual Clauses.
        </p>

        <h2>7) Retention</h2>
        <ul>
          <li>Enquiry data: up to 24 months (or longer if we work together).</li>
          <li>Analytics: as per GA settings (typically 14 months).</li>
          <li>Logs: up to 12 months.</li>
        </ul>

        <h2>8) Your rights (UK/EU)</h2>
        <p>
          You can request access, rectification, erasure, restriction, portability, or object. Where processing is based on
          consent, you may withdraw it anytime. Contact:&nbsp;
          <a href="mailto:contact@redhoodnova.com">contact@redhoodnova.com</a>. You may also complain to the ICO (UK).
        </p>

        <h2>9) Children</h2>
        <p>Our site is for business use; we do not knowingly collect children’s data.</p>

        <h2>10) Changes</h2>
        <p>We may update this notice; check the “Last updated” date above.</p>
      </section>
    </main>
  );
}
